cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'gist'
brew 'go'
brew 'grc'
brew 'hub'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'xctool'
brew 'youtube-dl'
brew 'zsh-syntax-highlighting'
brew 'git-flow'
brew 'fasd'
brew 'mergepbx'
