cask_args appdir: '/Applications'

brew "ack"
brew "readline"
brew "awscli"
brew "coreutils"
brew 'gist'
brew "git-flow"
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'wget'
brew 'zsh-syntax-highlighting'
brew 'git-flow'
cask 'tuist'
brew 'xcode-build-server'
brew 'gh'
brew 'nano'
cask 'amazon-q'
